services:
# Nginx Service
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - management
# Wordpress Service 
  wordpress:
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - management
# MariaDB Service
  mariadb:
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - management

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /home/lduthill/data/wordpress
      o: bind
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      device: /home/lduthill/data/mariadb
      o: bind

networks:
  management: